<?php
$config = $this->getConfig();
$base_url = $this->getUrl('');
$settings = $config->settings;
?>
<head>
	<title>Teach II Home Page</title>
	<!-- CSS -->
	<link rel="stylesheet" href="<?php echo $base_url.$settings["css_dir"]; ?>/styles.css">
	<link rel="stylesheet" href="<?php echo $base_url.$settings["css_dir"]; ?>/calendar.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
		  integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

	<!-- Font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

	<!-- JS -->
	<script src="<?php echo $base_url.$settings["js_dir"]; ?>/jquery.min.js"></script>
</head>

