<div class="register-component-wrap">
    <div class="form-wrap">
        <div class="register-banner-wrap">
            &nbsp;
        </div>
        <div class="register-form-wrap">
            <form method="post" action="/account/registerPost">
                <!--                account-->

                <div class="element-block">
                    <p class="label">
                        <span class="bullet">4</span> Configurations
                    </p>
                </div>

                <!--<div class="element-block">
                    <input class="input-item" name="username" type="text" required placeholder="Subject" value="" />
                </div>-->
                <div class="element-block">

                    <select required class="input-item" name="civil_status" placeholder="Civil Status">
                        <option class="initial" value="">Select Category</option>
                        <option value="single">Single</option>
                        <option value="married">Married</option>
                        <option value="widowed">Widowed</option>
                        <option value="divorced">Divorced</option>
                    </select>
                    <br/>
                    <br/>
                </div>
                <b/>


                <div class="element-block">
                    <input type="checkbox" /> <label class="sample-label">Required Response</label>
                </div>
                <div class="element-block">
                    <input type="checkbox" /> <label class="sample-label">Can Reply</label>
                </div>
                <div class="element-block">
                    <input type="checkbox" /> <label class="sample-label">Add to Calendar Schedule</label>
                    <br/>
                    <br/>
                </div>

                <div class="element-block">
                    <label class="sample-label">Start Date time</label>
                    <input class="input-item" name="date_of_birth" type="datetime-local" required placeholder="Start Date time" value="" />
                </div>
                <div class="element-block">
                    <label class="sample-label">End Date time</label>
                    <input class="input-item" name="date_of_birth" type="datetime-local" required placeholder="End Date time" value="" />
                </div>


                <!--                personal -->


                <!--<div class="element-block">

                    <select required class="input-item" name="civil_status" placeholder="Civil Status">
                        <option class="initial" value="">Select Civil Status</option>
                        <option value="single">Single</option>
                        <option value="married">Married</option>
                        <option value="widowed">Widowed</option>
                        <option value="divorced">Divorced</option>
                    </select>
                </div>-->





                <div class="element-block">
                    <button class="form-submit-button" type="submit">
                        <span>
                            NEXT>>>
                        </span>
                    </button>

                </div>
            </form>
        </div>
        <div class="crystal">&nbsp;</div>
    </div>
</div>
