<?php
$config = $this->getConfig();
$settings = $config->settings;
$base_url = $this->getUrl('');
$request = $_REQUEST;

/** @var User $model */
$model = Model::getModel('user');
?>

<div class="content-wrapper course">
    <div class="content">
        <div class="map">
            <img src="skins/default/images/courses-map.jpg" alt="Teach II Location Google Map" />
        </div>

        <div class="upcoming-courses courses" id="upcoming-courses">

            <div class="search">
                <div class="filter">
                    <span>Search</span>
                </div>
                <input type="text" placeholder="Find the class you're looking for">
                <a href="#" class="button search">
                    <i class="fa fa-search"></i>
                </a>
                <div class="search-content">
                    <div class="block categories">
                        <span class="title">Categories</span>

                        <div class="content">
                            <a href="javascript:void(0)"><span>Art</span></a>
                            <a href="javascript:void(0)"><span>Cooking</span></a>
                            <a href="javascript:void(0)"><span>Technology</span></a>
                            <a href="javascript:void(0)"><span>Lifestyle</span></a>
                            <a href="javascript:void(0)"><span>Music</span></a>
                            <a href="javascript:void(0)"><span>Language</span></a>
                            <a href="javascript:void(0)"><span>Performing Arts</span></a>
                        </div>
                    </div>

                    <div class="block date">
                        <span class="title">Date</span>
                        <div class="content">
                            <input type="date" name="start-date">
                            <input type="date" name="end-date">
                        </div>
                    </div>

                    <div class="block duration">
                        <span class="title">Duration</span>
                        <div class="content">
                            <a href="javascript:void(0)"><span>Single</span></a>
                            <a href="javascript:void(0)"><span>Multi-session</span></a>
                        </div>
                    </div>

                    <div class="block location">
                        <span class="title">Location</span>
                        <select>
                            <option value="">Select Location</option>
                            <option value="Filter 1">Location 1</option>
                            <option value="Filter 2">Location 2</option>
                            <option value="Filter 3">Location 3</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="sorter">
                <div class="filter">
                    <label>Sort By</label>

                    <div class="price">
                        <div class="clickable">
                            <span>Price</span>
                            <i class="fa fa-angle-down"></i>
                        </div>
                        <ul>
                            <li><a href="javascript:void(0)">Price 1</a></li>
                            <li><a href="javascript:void(0)">Price 2</a></li>
                            <li><a href="javascript:void(0)">Price 3</a></li>
                            <li><a href="javascript:void(0)">Price 4</a></li>
                        </ul>
                    </div>

                    <div class="date">
                        <div class="clickable">
                            <span>Date</span>
                            <i class="fa fa-angle-down"></i>
                        </div>
                        <ul>
                            <li><a href="javascript:void(0)">Date 1</a></li>
                            <li><a href="javascript:void(0)">Date 2</a></li>
                            <li><a href="javascript:void(0)">Date 3</a></li>
                            <li><a href="javascript:void(0)">Date 4</a></li>
                        </ul>
                    </div>
                </div>

                <div class="result">
                    <span>5 Results</span>
                </div>
            </div>

            <ul class="course">
                <li class="item">
                    <div class="item-wrapper">
                        <div class="top english">
                            <img src="<?php echo $settings["img_dir"]; ?>/profile.jpeg" />
                            <span class="time-start">Starts in 3 days</span>
                            <span class="type">Single</span>
                            <h1>English</h1>
                            <iframe width="834" height="556" src="https://www.youtube.com/embed/DoR0gqC6Oaw?rel=0&amp;showinfo=0"
                                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen></iframe>
                        </div>
                        <div class="bottom">
                    <span class="date">
                        <a class="fa fa-calendar-alt"></a><span>Oct. 8,2018</span>
                    </span>
                            <span class="time">
                        <a class="fa fa-clock"></a><span>10:00 ~ 11:30</span>
                    </span>
                            <span class="rate">
                        <a class="fa fa-tag"></a><span>TWD $1000</span>
                    </span>
                            <span class="rating">
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star-half-alt"></a>
                    </span>
                            <span class="wishlist">
                        <a class="fa fa-heart"></a>
                    </span>
                        </div>
                    </div>
                </li>

                <li class="item">
                    <div class="item-wrapper">
                        <div class="top english-culture">
                            <img src="<?php echo $settings["img_dir"]; ?>/profile.jpeg" />
                            <span class="time-start">Starts in 3 days</span>
                            <span class="type">Single</span>
                            <h1>English & Culture</h1>
                        </div>
                        <div class="bottom">
                    <span class="date">
                        <a class="fa fa-calendar-alt"></a><span>Oct. 8,2018</span>
                    </span>
                            <span class="time">
                        <a class="fa fa-clock"></a><span>10:00 ~ 11:30</span>
                    </span>
                            <span class="rate">
                        <a class="fa fa-tag"></a><span>TWD $1000</span>
                    </span>
                            <span class="rating">
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star-half-alt"></a>
                    </span>
                            <span class="wishlist">
                        <a class="fa fa-heart"></a>
                    </span>
                        </div>
                    </div>
                </li>

                <li class="item">
                    <div class="item-wrapper">
                        <div class="top game-tutor">
                            <img src="<?php echo $settings["img_dir"]; ?>/profile.jpeg" />
                            <span class="time-start">Starts in 3 days</span>
                            <span class="type">Single</span>
                            <h1>Game Tutor</h1>
                        </div>
                        <div class="bottom">
                    <span class="date">
                        <a class="fa fa-calendar-alt"></a><span>Oct. 8,2018</span>
                    </span>
                            <span class="time">
                        <a class="fa fa-clock"></a><span>10:00 ~ 11:30</span>
                    </span>
                            <span class="rate">
                        <a class="fa fa-tag"></a><span>TWD $1000</span>
                    </span>
                            <span class="rating">
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star-half-alt"></a>
                    </span>
                            <span class="wishlist">
                        <a class="fa fa-heart"></a>
                    </span>
                        </div>
                    </div>
                </li>

                <li class="item">
                    <div class="item-wrapper">
                        <div class="top english-tutoring">
                            <img src="<?php echo $settings["img_dir"]; ?>/profile.jpeg" />
                            <span class="time-start">Starts in 3 days</span>
                            <span class="type">Single</span>
                            <h1>English Tutoring</h1>
                        </div>
                        <div class="bottom">
                    <span class="date">
                        <a class="fa fa-calendar-alt"></a><span>Oct. 8,2018</span>
                    </span>
                            <span class="time">
                        <a class="fa fa-clock"></a><span>10:00 ~ 11:30</span>
                    </span>
                            <span class="rate">
                        <a class="fa fa-tag"></a><span>TWD $1000</span>
                    </span>
                            <span class="rating">
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star-half-alt"></a>
                    </span>
                            <span class="wishlist">
                        <a class="fa fa-heart"></a>
                    </span>
                        </div>
                    </div>
                </li>

                <li class="item">
                    <div class="item-wrapper">
                        <div class="top cooking">
                            <img src="<?php echo $settings["img_dir"]; ?>/profile.jpeg" />
                            <span class="time-start">Starts in 3 days</span>
                            <span class="type">Single</span>
                            <h1>Cooking</h1>
                        </div>
                        <div class="bottom">
                    <span class="date">
                        <a class="fa fa-calendar-alt"></a><span>Oct. 8,2018</span>
                    </span>
                            <span class="time">
                        <a class="fa fa-clock"></a><span>10:00 ~ 11:30</span>
                    </span>
                            <span class="rate">
                        <a class="fa fa-tag"></a><span>TWD $1000</span>
                    </span>
                            <span class="rating">
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star-half-alt"></a>
                    </span>
                            <span class="wishlist">
                        <a class="fa fa-heart"></a>
                    </span>
                        </div>
                    </div>
                </li>

                <li class="item">
                    <div class="item-wrapper">
                        <div class="top music">
                            <img src="<?php echo $settings["img_dir"]; ?>/profile.jpeg" />
                            <span class="time-start">Starts in 3 days</span>
                            <span class="type">Single</span>
                            <h1>Music</h1>
                        </div>
                        <div class="bottom">
                    <span class="date">
                        <a class="fa fa-calendar-alt"></a><span>Oct. 8,2018</span>
                    </span>
                            <span class="time">
                        <a class="fa fa-clock"></a><span>10:00 ~ 11:30</span>
                    </span>
                            <span class="rate">
                        <a class="fa fa-tag"></a><span>TWD $1000</span>
                    </span>
                            <span class="rating">
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star-half-alt"></a>
                    </span>
                            <span class="wishlist">
                        <a class="fa fa-heart"></a>
                    </span>
                        </div>
                    </div>
                </li>

                <li class="item">
                    <div class="item-wrapper">
                        <div class="top english-culture">
                            <img src="<?php echo $settings["img_dir"]; ?>/profile.jpeg" />
                            <span class="time-start">Starts in 3 days</span>
                            <span class="type">Single</span>
                            <h1>English & Culture</h1>
                        </div>
                        <div class="bottom">
                    <span class="date">
                        <a class="fa fa-calendar-alt"></a><span>Oct. 8,2018</span>
                    </span>
                            <span class="time">
                        <a class="fa fa-clock"></a><span>10:00 ~ 11:30</span>
                    </span>
                            <span class="rate">
                        <a class="fa fa-tag"></a><span>TWD $1000</span>
                    </span>
                            <span class="rating">
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star-half-alt"></a>
                    </span>
                            <span class="wishlist">
                        <a class="fa fa-heart"></a>
                    </span>
                        </div>
                    </div>
                </li>

                <li class="item">
                    <div class="item-wrapper">
                        <div class="top english">
                            <img src="<?php echo $settings["img_dir"]; ?>/profile.jpeg" />
                            <span class="time-start">Starts in 3 days</span>
                            <span class="type">Single</span>
                            <h1>English</h1>
                        </div>
                        <div class="bottom">
                    <span class="date">
                        <a class="fa fa-calendar-alt"></a><span>Oct. 8,2018</span>
                    </span>
                            <span class="time">
                        <a class="fa fa-clock"></a><span>10:00 ~ 11:30</span>
                    </span>
                            <span class="rate">
                        <a class="fa fa-tag"></a><span>TWD $1000</span>
                    </span>
                            <span class="rating">
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star"></a>
                        <a class="fa fa-star-half-alt"></a>
                    </span>
                            <span class="wishlist">
                        <a class="fa fa-heart"></a>
                    </span>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<script>
    jQuery(".content-wrapper.course .content .search div.filter > span").on('click', function () {
        jQuery(".upcoming-courses.courses").toggleClass('active');
    });
</script>